### ISSUE TITLE
How  can  I get  truly random  otp  sheets  for  encryption ?

### ISSUE THREAD

**Issue by bulcsu202002** [RabihND/SecretMsg#5]
You  said  python random  module  is  not  truly  random  so  it  can  be  cracked  easily    ,  but  how  can  I make  truly  random  sheets  for  encryption  ?

"The OTP relies on the randomness of the random number generator. If the generator isn’t truly random, then the OTP could be cracked. Python’s random module is probably not the best way of generating random numbers."

**Comment by RabihND** [comment]
Thank you for raising this important question. Indeed, the Python `random` module is not truly random as it's a PRNG. For cryptographic applications like OTP, we need a TRNG.

One solution is to use quantum random number generators (QRNGs), which utilize quantum mechanics to produce truly random numbers. While we can't simulate the full unpredictability of quantum phenomena on a classical computer, there are quantum computing platforms, such as Microsoft's Azure Quantum and Qiskit, that allow us to implement QRNGs in code.

Alternatively, for non-quantum solutions, we can use hardware-based RNGs or secure cryptographic functions from trusted libraries, which are designed to be unpredictable and suitable for encryption purposes.
